import {
  type Catalog,
  type DataReader,
  type NamedEntry,
  emptyCatalog
} from './catalog.js';
import { expandVariants } from './variants.js';
import { annotateSpellClasses } from './spellSources.js';
import { asNamedEntries } from './entries.js';
import { flattenRaces } from './mergeRace.js';

/**
 * Build a {@link Catalog} from an unpacked data tree.
 *
 * Single-file categories are read directly; index-driven ones (spells, classes)
 * follow their `index.json` to load every source file. Items combine three
 * sources: pre-made magic items, mundane base items, and variants generated by
 * expanding `magicvariants.json` against the base items. Missing files are
 * skipped so partial datasets still load.
 */
export function parseCatalog(reader: DataReader, version: string): Catalog {
  const catalog = emptyCatalog(version);

  catalog.entries.feat = readArray(reader, 'feats.json', 'feat');
  catalog.entries.background = readArray(reader, 'backgrounds.json', 'background');
  // Races: 5etools splits a playable race into a base race + subraces that merge
  // onto it. Flatten to single complete entries (see flattenRaces). Subraces are
  // read raw (not name-filtered) because the "standard" variant is nameless.
  catalog.entries.race = flattenRaces(
    readArray(reader, 'races.json', 'race'),
    readRaw(reader, 'races.json', 'subrace')
  );
  catalog.entries.action = readArray(reader, 'actions.json', 'action');
  catalog.entries.optionalfeature = readArray(
    reader,
    'optionalfeatures.json',
    'optionalfeature'
  );
  catalog.entries.condition = [
    ...readArray(reader, 'conditionsdiseases.json', 'condition'),
    ...readArray(reader, 'conditionsdiseases.json', 'disease'),
    ...readArray(reader, 'conditionsdiseases.json', 'status')
  ];

  catalog.entries.spell = readIndexed(reader, 'spells', 'spell');
  // Annotate spells with the classes/subclasses that grant them (reverse index).
  annotateSpellClasses(
    catalog.entries.spell,
    reader.json('generated/gendata-spell-source-lookup.json')
  );
  catalog.entries.class = readIndexed(reader, 'class', 'class');
  catalog.classData = readClassData(reader);
  catalog.entries.item = readItems(reader);

  for (const category of Object.keys(catalog.entries) as (keyof typeof catalog.entries)[]) {
    catalog.counts[category] = catalog.entries[category].length;
  }
  return catalog;
}

/** Read `prop` array from a single JSON file, keeping only valid named entries. */
function readArray(reader: DataReader, path: string, prop: string): NamedEntry[] {
  const data = reader.json<Record<string, unknown>>(path);
  return asNamedEntries(data?.[prop]);
}

/** Read `prop` as a raw object array, without the name+source filter. */
function readRaw(reader: DataReader, path: string, prop: string): Record<string, unknown>[] {
  const data = reader.json<Record<string, unknown>>(path);
  const value = data?.[prop];
  return Array.isArray(value) ? (value.filter((e) => e && typeof e === 'object') as Record<string, unknown>[]) : [];
}

/**
 * Read every source file listed in `<dir>/index.json` and concatenate their
 * `prop` arrays. Used for spells and classes, which are split per source book.
 */
function readIndexed(reader: DataReader, dir: string, prop: string): NamedEntry[] {
  const index = reader.json<Record<string, string>>(`${dir}/index.json`);
  if (!index) return [];
  const out: NamedEntry[] = [];
  for (const file of Object.values(index)) {
    const data = reader.json<Record<string, unknown>>(`${dir}/${file}`);
    out.push(...asNamedEntries(data?.[prop]));
  }
  return out;
}

/** Gather classFeature/subclassFeature/subclass arrays across all class files. */
function readClassData(reader: DataReader) {
  const index = reader.json<Record<string, string>>('class/index.json');
  const classFeature: NamedEntry[] = [];
  const subclassFeature: NamedEntry[] = [];
  const subclass: NamedEntry[] = [];
  if (index) {
    for (const file of Object.values(index)) {
      const data = reader.json<Record<string, unknown>>(`class/${file}`);
      classFeature.push(...asNamedEntries(data?.classFeature));
      subclassFeature.push(...asNamedEntries(data?.subclassFeature));
      subclass.push(...asNamedEntries(data?.subclass));
    }
  }
  return { classFeature, subclassFeature, subclass };
}

/** Combine pre-made magic items, base items, and expanded variants. */
function readItems(reader: DataReader): NamedEntry[] {
  const items = reader.json<Record<string, unknown>>('items.json');
  const base = reader.json<Record<string, unknown>>('items-base.json');
  const variantsFile = reader.json<Record<string, unknown>>('magicvariants.json');

  const magicItems = asNamedEntries(items?.item);
  const baseItems = asNamedEntries(base?.baseitem);
  const variants = Array.isArray(variantsFile?.magicvariant)
    ? (variantsFile!.magicvariant as Parameters<typeof expandVariants>[1])
    : [];

  // Overlapping variant templates can generate the same item twice; dedupe by
  // name+source, keeping the first occurrence (base/premade win over variants).
  return dedupeByNameSource([
    ...baseItems,
    ...magicItems,
    ...expandVariants(baseItems, variants)
  ]);
}

function dedupeByNameSource(entries: NamedEntry[]): NamedEntry[] {
  const seen = new Set<string>();
  const out: NamedEntry[] = [];
  for (const entry of entries) {
    const key = `${entry.name} ${entry.source}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(entry);
  }
  return out;
}
